// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// exactMassMatchCpp
List exactMassMatchCpp(List Res, NumericVector unknowns, NumericVector metMasses, CharacterVector metMassesNames, double ppm, double mill);
RcppExport SEXP compMS2Miner_exactMassMatchCpp(SEXP ResSEXP, SEXP unknownsSEXP, SEXP metMassesSEXP, SEXP metMassesNamesSEXP, SEXP ppmSEXP, SEXP millSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type Res(ResSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type unknowns(unknownsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type metMasses(metMassesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type metMassesNames(metMassesNamesSEXP);
    Rcpp::traits::input_parameter< double >::type ppm(ppmSEXP);
    Rcpp::traits::input_parameter< double >::type mill(millSEXP);
    rcpp_result_gen = Rcpp::wrap(exactMassMatchCpp(Res, unknowns, metMasses, metMassesNames, ppm, mill));
    return rcpp_result_gen;
END_RCPP
}
