# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

exactMassMatchCpp <- function(Res, unknowns, metMasses, metMassesNames, ppm, mill) {
    .Call('compMS2Miner_exactMassMatchCpp', PACKAGE = 'compMS2Miner', Res, unknowns, metMasses, metMassesNames, ppm, mill)
}

